- name: "breaking change"
  color: "ff0205"
  description: "This change will require a major version bump"
- name: "blocked"
  color: "e11d21"
  description: "This issue is blocked by another issue"
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "environment"
  color: "703E17"
  description: "Improvement, to infra or build environment"
- name: "feature"
  color: "fbca04"
  description: "A new business feature"
- name: "in progress"
  color: "5ae1c2"
  description: "In flight work"
- name: "next release"
  color: "5319e7"
  description: "Completed work that is yet to be deployed"
- name: "technical debt"
  color: "c19337"
  description: "An issue describing some techinal debt that needs to be addressed in the future"
- name: "to do"
  color: "fbca04"
  description: "Work that is yet to be started"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "wontfix"
  color: "ffffff"
  description: "The project maintainers have decided this will not be worked on"
- name: "request"
  color: "0366d6"
  description: "A request for a new feature or enhancement"
- name: "awaiting review"
  color: "fbca04"
  description: "This pull request is awaiting review"
- name: "priority:critical"
  color: "b60205"
  description: "This issue is critical to the business"
- name: "priority:high"
  color: "d93f0b"
  description: "This issue is high priority"
- name: "priority:medium"
  color: "fbca04"
  description: "This issue is medium priority"
- name: "priority:low"
  color: "0e8a16"
  description: "This issue is low priority"
- name: "awaiting feedback"
  color: "fbca04"
  description: "This issue is awaiting feedback from the reporter"
- name: "stale"
  color: "eeeeee"
  description: "This issue/PR has been inactive for too long"