version: 1.0.{build}
skip_tags: true
configuration: Release
build:
  publish_nuget: true
  verbosity: minimal
environment:
  Test.Path: C:\projects\sitewarmer\SiteWarmer\
  GithubEmail: baynezy@gmail.com
  GithubUsername: baynezy
  GithubPersonalAccessToken:
    secure: 9EkZYUVbHPWlMZLyUqjY79llLHc6DghntcHAodFfiMyOsIc4pbCNNEMv/lTi0SvJ
artifacts:
- path: \SiteWarmer\SiteWarmer.App\bin\Release\output\SiteWarmer.exe
  name: release
deploy:
- provider: NuGet
  api_key:
    secure: mqfd5QXj3a2N+D2EP9avxupQJRBJFEKT9kjF7Tipl1OCkUvPBsKjfiZMQHpnwVKq
  on:
    branch: master
install:
  - choco install doxygen.portable
after_test:
  - ps: C:/ProgramData/chocolatey/lib/doxygen.portable/tools/doxygen.exe doxygen.config
  - ps: ./pushDocumentation.ps1 $env:APPVEYOR_BUILD_FOLDER $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken $env:appveyor_repo_branch
deploy_script:
  - ps: ./addVersionToEnvironment.ps1
notifications:
  - provider: Slack
    auth_token:
      secure: xLrYwFJVzehV+sdSJsDp52X1TSPeSGJrr56LI2GQDvrmkpjcrwX1rmPwdH+i14H8lijQDcWbUt9jl81saehgRA==
    channel: '#build'