name: Configure GitHub Issue Labels

on:
  push:
    paths:
      - ".github/workflows/label-configurer.yml"
      - ".github/labels.yml"

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude: |
            *min review