name: "Release"

on:
  push:
    tags:
      - "**"

jobs:
  get-version:
    uses: ./.github/workflows/step-version.yml
    with:
      static-build: true
      
  release:
    needs: [get-version]
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Build Artifact"
        run: |
          dotnet publish ./src/Console/Console.csproj -c Release -r win-x64 -o ./output /p:Version=${{ needs.get-version.outputs.version }}

      - name: "Create Release"
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.CREATE_RELEASE_TOKEN }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            ./output/SiteWarmer.exe