on:
  workflow_call:
    inputs:
      version:
        required: true
        description: 'Version to deploy'
        type: string
  
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create tag
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "no-reply@after-life.co"
          git tag -a ${{ inputs.version }} -m "Version ${{ inputs.version }} created via GitHub Actions"
          git push origin ${{ inputs.version }}